[changelog]
header = "## Changelog"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper }}

{% for commit in commits %}
- {{ commit.message | trim }}
{% endfor %}
{% endfor %}
"""

footer = ""

[git]
conventional_commits = false
filter_unconventional = false

commit_parsers = [
  { message = "^Merge", skip = true },
  { message = "^Bump version", skip = true },
  { message = "^Update changelog", skip = true },
  { message = "^Test", skip = true },
  { message = "(?i).*feat.*", group = "Features" },
  { message = "(?i).*fix.*", group = "Fixes" },
  { message = "(?i).*doc.*", group = "Documentation" },
  { message = "(?i).*style.*", group = "Internal" },
  { message = "(?i).*polish.*", group = "Internal" },
  { message = ".*", group = "Other" }
]
